name: CI

on:
  workflow_dispatch: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install pnpm
        run: |
          npm install -g pnpm

      - name: Install dependencies
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate
          pnpm install

      - name: Build client
        run: pnpm --filter @app/website build

      - name: Build server
        run: pnpm --filter @app/server build
      - name: Build client
        run: pnpm --filter @app/website build

      - name: Build server
        run: pnpm --filter @app/server build
